import { prisma } from '../lib/prisma';
import { readFileSync } from 'fs';
import { join } from 'path';

interface CompanyRow {
  no: string;
  name: string;
  npwp: string;
  address: string;
}

async function importCompanies() {
  const csvPath = join(process.cwd(), '../../context/simonKlien.csv');
  const csvContent = readFileSync(csvPath, 'utf-8');

  // Parse CSV - skip first 2 empty rows and header row
  const lines = csvContent.split('\n').slice(3);

  const companies: CompanyRow[] = [];

  for (const line of lines) {
    if (!line.trim()) continue;

    // Split by semicolon and extract relevant columns
    const parts = line.split(';');

    // CSV structure: ;;No.;Nama Klien;NPWP;Alamat
    // So indices are: [0]='', [1]='', [2]=No, [3]=Name, [4]=NPWP, [5]=Address
    if (parts.length >= 6) {
      const no = parts[2]?.trim();
      const name = parts[3]?.trim();
      const npwp = parts[4]?.trim();
      const address = parts[5]?.trim();

      if (name && npwp) {
        companies.push({ no, name, npwp, address });
      }
    }
  }

  console.log(`Found ${companies.length} companies to import`);

  let imported = 0;
  let skipped = 0;
  let errors = 0;

  for (const company of companies) {
    try {
      // Check if already exists
      const existing = await prisma.party.findFirst({
        where: {
          displayName: company.name,
          deletedAt: null
        }
      });

      if (existing) {
        console.log(`⏭️  Skipped: ${company.name} (already exists)`);
        skipped++;
        continue;
      }

      // Create party
      await prisma.party.create({
        data: {
          displayName: company.name,
          nameNormalized: '', // Auto-generated by trigger
          tinDisplay: company.npwp,
          tinNormalized: '', // Auto-generated by trigger
          partyType: 'buyer',
          countryCode: 'IDN', // Indonesian companies
          addressFull: company.address || null,
          email: null,
          buyerDocument: 'TIN',
          buyerDocumentNumber: null,
          buyerIdtku: null, // Auto-calculated
          sellerId: null,
          createdBy: 'CSV_IMPORT'
        }
      });

      console.log(`✅ Imported: ${company.name}`);
      imported++;

    } catch (error: any) {
      console.error(`❌ Error importing ${company.name}:`, error.message);
      errors++;
    }
  }

  console.log('\n=== Import Summary ===');
  console.log(`Total companies: ${companies.length}`);
  console.log(`Imported: ${imported}`);
  console.log(`Skipped: ${skipped}`);
  console.log(`Errors: ${errors}`);

  await prisma.$disconnect();
}

importCompanies().catch((error) => {
  console.error('Fatal error:', error);
  process.exit(1);
});
